# Agents configuration (Hello World style)
# You can add more agents by following this structure.
#
# Tools configuration notes:
# - You can specify tools as a list of strings (existing behavior), including wildcards (e.g., "brave_search.*").
# - You can also specify tools as objects to enable per-tool options, for example:
#     tools:
#       - { name: "web_rag", result_as_answer: true }  # Tool output becomes the agent's answer
#       - "file_write"                                 # Strings still supported
# - Legacy key 'tool_names' remains supported and behaves like a list of strings.

researcher:
  role: "Researcher"
  goal: "Find concise facts on {topic}"
  backstory: "Efficient analyst focused on brevity."
  verbose: false
  allow_delegation: true
  enabled: true
  tool_names: ["web_rag","file_write"]
  # LLM alias recognized by CrewAI/llms(), API key via OPENAI_API_KEY
  llm: gpt-4o-mini
  # Optional: LLM temperature (0-2), defaults to CrewAI default
  llm_temperature: 0
  # Optional: enable built-in caching for this agent (supported CrewAI versions only)
  # cache: true
  # Optional: enable interactive human input prompts for this agent (if supported)
  # human_input: true
  # Optional: allow the agent to execute code (ensure sandboxing as needed)
  # allow_code_execution: false
  # Optional: enable multimodal capabilities if supported by the underlying LLM
  # multimodal: true
  # Optional: rate limiting and iteration control
  # max_rpm: null
  max_iter: 5

report_writer:
  role: "Writer"
  goal: "Write a brief report on the provided content as output file"
  backstory: "Clear, concise writer."
  verbose: true
  allow_delegation: false
  enabled: true
  tool_names: ["file_read","file_write"]
  llm: gpt-4o-mini
  max_iter: 5

summary_analyst:
  role: "Summarizer"
  goal: "Summarize provided content briefly"
  backstory: "Expert at concise summaries."
  verbose: true
  allow_delegation: false
  enabled: false
  tool_names: ["file_read","file_write"]
  llm: gpt-4o-mini
  max_iter: 5