# Agents configuration (Hello World style)
# You can add more agents by following this structure.

researcher:
  role: "Market Research Analyst"
  goal: "Provide up-to-date analysis about {topic}"
  backstory: "An expert analyst with a keen eye for market trends."
  verbose: true
  allow_delegation: false
  enabled: true
  tool_names: ["web_rag","scrape_website","scrape_element"]
  # LLM alias recognized by CrewAI/llms(), API key via OPENAI_API_KEY
  llm: gpt-4o-mini
  # Optional: LLM temperature (0-2), defaults to CrewAI default
  llm_temperature: 0.2
  # Optional: enable built-in caching for this agent (supported CrewAI versions only)
  # cache: true
  # Optional: disable interactive human input prompts for this agent (if supported)
  # human_input: false
  # Optional: allow the agent to execute code (ensure sandboxing as needed)
  # allow_code_execution: false
  # Optional: enable multimodal capabilities if supported by the underlying LLM
  # multimodal: true
  # Optional: rate limiting and iteration control
  # max_rpm: null
  # max_iter: 25

reporting_analyst:
  role: "Content Writer"
  goal: "Craft exceptional, clear reports about {topic}"
  backstory: "A skilled writer with a passion for new and promising trends."
  verbose: true
  allow_delegation: false
  enabled: true
  tool_names: ["file_read", "dir_read"]
  llm: gpt-4o

summary_analyst:
  role: "Content Summarizer"
  goal: "Summarize the provided content"
  backstory: "A skilled writer with an exceptional skill to summarize reports."
  verbose: true
  allow_delegation: false
  enabled: true
  tool_names: ["file_read", "dir_read"]
  llm: gpt-4o