# Crew-wide settings and defaults
process: sequential  # options: sequential, hierarchical
verbose: true
planning: true
memory: true
planning_llm: gpt-4o-mini
knowledge: {}

# Tool configuration files (merged in order)
tools_files:
  - config/tools.yaml
  - config/mcp_tools.yaml
