# Multi-crew configuration (root mapping)
crews:
  default:
    # Crew-wide settings and defaults
    process: sequential  # options: sequential, hierarchical
    verbose: false
    planning: false
    memory: false
    planning_llm: gpt-4o-mini

    # Optional: specify a manager agent by name (must match an agent key in agents.yaml)
    # Manager LLM used to manage the crew (applies when hierarchical or when used explicitly)
    # manager_agent: summary_analyst
    # IMPORTANT: Either manager_agent or manager_llm must be set when using the hierarchical process.
    manager_llm: gpt-4o-mini

    # Knowledge sources configuration
    # List of knowledge sources to use from agents.knowledge.yaml
    # Semantics:
    # - omit key or set to ["ALL"] => use all available
    # - [] => use none
    # - [names...] => only those listed
    knowledge_sources: []  # e.g. ["ALL"] or ["user_profile", "company_policies"]

    # When true, CLI runs kickoff asynchronously
    run_async: false

    # Tool configuration files (merged in order)
    tools_files:
      - config/tools.yaml
      - config/mcp_tools.yaml

    # Crew-level orchestration (config-driven)
    # Only these agents will be instantiated for this crew
    agents:
      - researcher
      - report_writer

    # Explicit task execution order for this crew
    task_order:
      - web_content_research_task
      - reporting_task

    # Explicitly map tasks to agents
    task_agent_map:
      web_content_research_task: researcher
      reporting_task:
      - researcher
      - report_writer
    observability:
      enabled: true
      provider: phoenix
      instrument_crewai: true
      instrument_openai: false
      otlp_endpoint: http://127.0.0.1:4318
      launch_ui: true

  crew_composer:
    process: sequential
    verbose: true
    planning: true
    memory: false
    planning_llm: gpt-4o-mini
    knowledge_sources:
      - crew_design_checklist
      - crewai_reference_web
      - yaml_style_guide
      - observability_best_practices
    run_async: false
    tools_files:
      - config/tools.yaml
      - config/mcp_tools.yaml
    agents:
      - requirements_interviewer
      - crew_architect
      - agent_designer
      - task_planner
      - config_validator
    task_order:
      - requirements_intake_task
      - architecture_proposal_task
      - agents_yaml_task
      - tasks_yaml_task
      - crew_yaml_task
      - knowledge_recommendations_task
      - tool_recommendations_task
      - validation_task
      - runbook_task
    task_agent_map:
      requirements_intake_task: requirements_interviewer
      architecture_proposal_task: crew_architect
      agents_yaml_task:
        - crew_architect
        - agent_designer
      tasks_yaml_task:
        - crew_architect
        - task_planner
      crew_yaml_task: crew_architect
      knowledge_recommendations_task: crew_architect
      tool_recommendations_task:
        - crew_architect
        - agent_designer
      validation_task: config_validator
      runbook_task:
        - config_validator
        - crew_architect
