# Crew-wide settings and defaults
process: hierarchical  # options: sequential, hierarchical
verbose: true
planning: true
memory: true
planning_llm: gpt-4o-mini
knowledge: {}

# Knowledge sources configuration
# List of knowledge sources to use from agents.knowledge.yaml
# Leave empty to use all sources, or specify specific source names
knowledge_sources: ["news_article_guidelines"]  # e.g. ["user_profile", "company_policies"]
run_async: false  # when true, CLI runs kickoff asynchronously

# Optional: specify a manager agent by name (must match an agent key in agents.yaml)
# Manager LLM used to manage the crew (applies when hierarchical or when used explicitly)
# manager_agent: summary_analyst
# IMPORTANT: Either manager_agent or manager_llm must be set when using the hierarchical process.
manager_llm: gpt-4o-mini


# Tool configuration files (merged in order)
tools_files:
  - config/tools.yaml
  - config/mcp_tools.yaml
