# Tools configuration. Tools are grouped by category for clarity.
# Only tools with enabled: true are instantiated.

tools:
  file_document_management:
    - name: file_read
      module: crewai_tools
      class: FileReadTool
      enabled: true
      args: {}

    - name: dir_read
      module: crewai_tools
      class: DirectoryReadTool
      enabled: false
      args:
        directory: output

    - name: file_write
      module: crewai_tools
      class: FileWriterTool
      enabled: true
      args:
        directory: output
    - name: dir_search
      module: crewai_tools
      class: DirectorySearchTool
      enabled: false
      args:
        directory: output

    - name: pdf_search
      module: crewai_tools
      class: PDFSearchTool
      enabled: false
      args: {}

    - name: docx_search
      module: crewai_tools
      class: DOCXSearchTool
      enabled: false
      args: {}

    - name: csv_search
      module: crewai_tools
      class: CSVSearchTool
      enabled: false
      args: {}

    - name: txt_search
      module: crewai_tools
      class: TXTSearchTool
      enabled: false
      args: {}

    - name: json_search
      module: crewai_tools
      class: JSONSearchTool
      enabled: false
      args: {}

    - name: mdx_search
      module: crewai_tools
      class: MDXSearchTool
      enabled: false
      args: {}

  web_scraping_browsing:
    - name: web_rag
      module: crewai_tools
      class: WebsiteSearchTool
      enabled: true
      args: {}

    - name: scrape_website
      module: crewai_tools
      class: ScrapeWebsiteTool
      enabled: true
      args: {}

    - name: scrape_element
      module: crewai_tools
      class: ScrapeElementFromWebsiteTool
      enabled: true
      args: {}

    - name: firecrawl_search
      module: crewai_tools
      class: FirecrawlSearchTool
      enabled: false
      args: {}
      env:
        FIRECRAWL_API_KEY: ${FIRECRAWL_API_KEY}

    - name: firecrawl_scrape
      module: crewai_tools
      class: FirecrawlScrapeWebsiteTool
      enabled: false
      args: {}
      env:
        FIRECRAWL_API_KEY: ${FIRECRAWL_API_KEY}

    - name: firecrawl_crawl
      module: crewai_tools
      class: FirecrawlCrawlWebsiteTool
      enabled: false
      args: {}
      env:
        FIRECRAWL_API_KEY: ${FIRECRAWL_API_KEY}

    - name: selenium_scrape
      module: crewai_tools
      class: SeleniumScrapingTool
      enabled: false
      args: {}

    - name: serper_scrape
      module: crewai_tools
      class: SerperScrapeWebsiteTool
      enabled: false
      args: {}
      env:
        SERPER_API_KEY: ${SERPER_API_KEY}

  search_research:
    - name: search
      module: crewai_tools
      class: SerperDevTool
      enabled: false
      args: {}
      env:
        SERPER_API_KEY: ${SERPER_API_KEY}

    - name: tavily_search
      module: crewai_tools
      class: TavilySearchTool
      enabled: false
      args: {}
      env:
        TAVILY_API_KEY: ${TAVILY_API_KEY}

    - name: brave_search
      module: crewai_tools
      class: BraveSearchTool
      enabled: false
      args: {}
      env:
        BRAVE_API_KEY: ${BRAVE_API_KEY}

    - name: serpapi_search
      module: crewai_tools
      class: SerpApiGoogleSearchTool
      enabled: false
      args: {}
      env:
        SERPAPI_API_KEY: ${SERPAPI_API_KEY}

    - name: youtube_video_search
      module: crewai_tools
      class: YoutubeVideoSearchTool
      enabled: false
      args: {}
      env:
        YOUTUBE_API_KEY: ${YOUTUBE_API_KEY}

    - name: youtube_channel_search
      module: crewai_tools
      class: YoutubeChannelSearchTool
      enabled: false
      args: {}
      env:
        YOUTUBE_API_KEY: ${YOUTUBE_API_KEY}

    - name: github_search
      module: crewai_tools
      class: GithubSearchTool
      enabled: false
      args: {}
      env:
        GITHUB_TOKEN: ${GITHUB_TOKEN}

    - name: arxiv_papers
      module: crewai_tools
      class: ArxivPaperTool
      enabled: false
      args: {}

  database_data_management:
    - name: qdrant_search
      module: crewai_tools
      class: QdrantVectorSearchTool
      enabled: false
      args:
        host: ${QDRANT_HOST:localhost}
        port: ${QDRANT_PORT:6333}
        collection_name: ${QDRANT_COLLECTION}

    - name: mysql_search
      module: crewai_tools
      class: MySQLSearchTool
      enabled: false
      args: 
        db_uri: mysql://user:password@localhost:3306/mydatabase
        table_name: mytable
      
    - name: weaviate_search
      module: crewai_tools
      class: WeaviateVectorSearchTool
      enabled: false
      args: {}
      env:
        WEAVIATE_URL: ${WEAVIATE_URL}
        WEAVIATE_API_KEY: ${WEAVIATE_API_KEY}

    - name: mongodb_vector_search
      module: crewai_tools
      class: MongoDBVectorSearchTool
      enabled: false
      args: {}
      env:
        MONGODB_URI: ${MONGODB_URI}

    - name: pg_search
      module: crewai_tools
      class: PGSearchTool
      enabled: false
      args: {}
      env:
        PGHOST: ${PGHOST}
        PGPORT: ${PGPORT:5432}
        PGUSER: ${PGUSER}
        PGPASSWORD: ${PGPASSWORD}
        PGDATABASE: ${PGDATABASE}

    - name: singlestore_search
      module: crewai_tools
      class: SingleStoreSearchTool
      enabled: false
      args: {}

    - name: snowflake_search
      module: crewai_tools
      class: SnowflakeSearchTool
      enabled: false
      args: {}
      env:
        SNOWFLAKE_ACCOUNT: ${SNOWFLAKE_ACCOUNT}
        SNOWFLAKE_USER: ${SNOWFLAKE_USER}
        SNOWFLAKE_PASSWORD: ${SNOWFLAKE_PASSWORD}

    - name: couchbase_vector_search
      module: crewai_tools
      class: CouchbaseFTSVectorSearchTool
      enabled: false
      args: {}
      env:
        COUCHBASE_CONNECTION_STRING: ${COUCHBASE_CONNECTION_STRING}
        COUCHBASE_USERNAME: ${COUCHBASE_USERNAME}
        COUCHBASE_PASSWORD: ${COUCHBASE_PASSWORD}
        COUCHBASE_BUCKET: ${COUCHBASE_BUCKET}

  ai_machine_learning:
    - name: dalle_generate
      module: crewai_tools
      class: DallETool
      enabled: false
      args: {}
      env:
        OPENAI_API_KEY: ${OPENAI_API_KEY}

    - name: vision_extract_text
      module: crewai_tools
      class: VisionTool
      enabled: false
      args: {}
      env:
        OPENAI_API_KEY: ${OPENAI_API_KEY}
    
    # Install dependency minds-sdk.
    - name: aimind_query
      module: crewai_tools
      class: AIMindTool
      enabled: false
      args: {}
      env:
        MINDS_API_KEY: ${MINDS_API_KEY}

    - name: rag_knowledge_base
      module: crewai_tools
      class: RagTool
      enabled: false
      args: {}

    # Default is safe (Docker if available, else sandbox).
    # You can set args.unsafe_mode: true only if you accept the HIGH risk.
    - name: code_interpreter
      module: crewai_tools
      class: CodeInterpreterTool
      enabled: false
      args: {}

    # Install dependency llama-index.
    - name: llamaindex_tool
      module: crew_composer.tools.llamaindex_query_tool
      class: LlamaIndexQueryTool
      enabled: false
      args: {}
      # Optional usage examples (uncomment and adjust):
      # args:
      #   data_dir: "knowledge/"  # builds a simple index from files in this dir
      #   # OR use a factory to return a prebuilt query engine
      #   # factory_path: "your_package.builders:build_query_engine"
      #   # factory_kwargs: { index_name: "my_index" }

  cloud_storage_solutions:
    - name: s3_read
      module: crewai_tools
      class: S3ReaderTool
      enabled: false
      args: {}
      env:
        AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
        AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
        AWS_REGION: ${AWS_REGION:us-east-1}
        AWS_S3_BUCKET: ${AWS_S3_BUCKET}

    - name: s3_write
      module: crewai_tools
      class: S3WriterTool
      enabled: false
      args: {}
      env:
        AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
        AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
        AWS_REGION: ${AWS_REGION:us-east-1}
        AWS_S3_BUCKET: ${AWS_S3_BUCKET}

  automation_integration:
    - name: zapier_action
      module: crewai_tools
      class: ZapierActionTool
      enabled: false
      args: {}
      env:
        ZAPIER_NLA_API_KEY: ${ZAPIER_NLA_API_KEY}

    - name: multion_action
      module: crewai_tools
      class: MultiOnTool
      enabled: false
      args: {}
      env:
        MULTION_API_KEY: ${MULTION_API_KEY}

    - name: composio_action
      module: crewai_tools
      class: ComposioTool
      enabled: false
      args: {}
      env:
        COMPOSIO_API_KEY: ${COMPOSIO_API_KEY}

  scheduling:
    - name: schedule_manager
      module: crew_composer.tools.schedule_tool
      class: ScheduleManagerTool
      enabled: false
      args: {}
      # Optional defaults (example):
      # args:
      #   default_crew: "your_crew_name"
      #   default_trigger: "interval"
      #   default_timezone: "UTC"
